language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
script:
  - cargo test
matrix:
  include:
    - rust: stable
      env: RUN=RUSTFMT
      before_script: rustup component add rustfmt-preview
      script: cargo fmt --all -- --write-mode=diff
