language: rust
sudo: false
cache: cargo
before_script:
- cargo install -f rustfmt
- export PATH=$PATH:$HOME/.cargo/bin
rust:
- nightly
- beta
- stable
matrix:
  allow_failures:
  - rust: nightly
script:
- cargo fmt -- --check
- cargo build --verbose
- cargo test --verbose
