language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
env:
  - RUN=TEST
script:
  - cargo test
matrix:
  include:
    - rust: nightly
      env: RUN=RUSTFMT
      before_script: rustup component add rustfmt-preview
      script: cargo fmt --all -- --check
  allow_failures:
    - rust: nightly
      env: RUN=TEST
